"""Initial schema

Revision ID: c6166ae883d4
Revises: 'None'
Create Date: 2026-09-06 20:00:39.234237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6166ae883d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('author_reference', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('permission_granted', sa.Boolean(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('demand_signals',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('author_reference', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_demand_signals_fingerprint'), 'demand_signals', ['fingerprint'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('offers',
    sa.Column('offer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('shipping_destination', sa.String(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('purchase_intents',
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('extracted_requirements', sa.JSON(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['demand_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_table('outreach_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('response_received', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['purchase_intents.intent_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach_messages')
    op.drop_table('purchase_intents')
    op.drop_table('offers')
    op.drop_table('products')
    op.drop_index(op.f('ix_demand_signals_fingerprint'), table_name='demand_signals')
    op.drop_table('demand_signals')
    op.drop_table('contacts')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
